In [2]:
import glob
#The glob function in Python is a part of the built-in glob module used to find all file pathnames matching a specified pattern

In [3]:
glob.glob('retail_db/**',recursive = True)


#- retail_db/ -> start searching inside this folder
#- ** -> go inside all subfolder. 2 astrik(*) means folder inside 1 subfolder than another subfolder
#- recursive = True -> allow to work recursively

['retail_db\\',
 'retail_db\\categories',
 'retail_db\\categories\\part-00000.txt',
 'retail_db\\customers',
 'retail_db\\customers\\part-000001.txt',
 'retail_db\\departments',
 'retail_db\\departments\\part-00000.txt',
 'retail_db\\departments\\test1.csv',
 'retail_db\\departments\\test2.csv',
 'retail_db\\orders',
 'retail_db\\orders\\part-00000.txt',
 'retail_db\\order_items',
 'retail_db\\order_items\\part-order_items.txt',
 'retail_db\\products',
 'retail_db\\products\\part-products.txt',
 'retail_db\\schemas.json',
 'retail_db\\simple.json']

In [4]:
src_file_name = glob.glob("retail_db/*/part-*")
src_file_name

['retail_db\\categories\\part-00000.txt',
 'retail_db\\customers\\part-000001.txt',
 'retail_db\\departments\\part-00000.txt',
 'retail_db\\orders\\part-00000.txt',
 'retail_db\\order_items\\part-order_items.txt',
 'retail_db\\products\\part-products.txt']

In [5]:
s = 'a\\b\\c'
s

'a\\b\\c'

In [6]:
s.split('/')

['a\\b\\c']

In [7]:
import re
re.split(r'\\',s)

['a', 'b', 'c']

<h3><u>What is re?</u></h3>

<p><b>re</b> is <b>Regular expression(regex)</b> is just a pattern for matching text.</p>
<p>It is a built-in python library that lets you:</p>
<ul>
    <li>Search text</li>
    <li>Match patterns</li>
    <li>Split text using patterns</li>
    <li>Replace parts of text</li>
</ul>

In [8]:
for file in src_file_name:
    print(re.split(r'\\',file))

['retail_db', 'categories', 'part-00000.txt']
['retail_db', 'customers', 'part-000001.txt']
['retail_db', 'departments', 'part-00000.txt']
['retail_db', 'orders', 'part-00000.txt']
['retail_db', 'order_items', 'part-order_items.txt']
['retail_db', 'products', 'part-products.txt']

In [9]:
for file in src_file_name:
    file_path_list = re.split(r'\\',file)
    print(file_path_list)

['retail_db', 'categories', 'part-00000.txt']
['retail_db', 'customers', 'part-000001.txt']
['retail_db', 'departments', 'part-00000.txt']
['retail_db', 'orders', 'part-00000.txt']
['retail_db', 'order_items', 'part-order_items.txt']
['retail_db', 'products', 'part-products.txt']

In [10]:
base_dir= 'retail_db_json'

In [11]:
file = src_file_name[0]

file_path_list = re.split(r'\\',file)
db_name = file_path_list[-2]
db_name

'categories'

In [12]:
import pandas as pd

In [13]:
for file_name in src_file_name:
    df = pd.read_csv(file_name , header = None)
    print(f"Shape of {file_name} is {df.shape}")

Shape of retail_db\categories\part-00000.txt is (58, 3)
Shape of retail_db\customers\part-000001.txt is (12435, 9)
Shape of retail_db\departments\part-00000.txt is (6, 2)
Shape of retail_db\orders\part-00000.txt is (68883, 4)
Shape of retail_db\order_items\part-order_items.txt is (172198, 6)
Shape of retail_db\products\part-products.txt is (1345, 6)

In [14]:
import json

In [15]:
def get_column_name(schemas, df_name, sorting_key = 'column_position'):
    column_details = schemas[df_name]
    column = sorted(column_details,key=lambda col: col[sorting_key])
    return[col['column_name'] for col in column]

In [16]:
schemas = json.load(open(r"D:\Khushi\course\python\mini project\retail_db\schemas.json"))

In [17]:
categories_columns = get_column_name(schemas , 'categories')
categories_columns

['category_id', 'category_department_id', 'category_name']

In [18]:
departments_columns = get_column_name(schemas , 'departments')
departments_columns

['department_id', 'department_name']

In [19]:
categories = pd.read_csv('retail_db/categories/part-00000.txt',names = categories_columns)
categories

    category_id  category_department_id         category_name
0             1                       2              Football
1             2                       2                Soccer
2             3                       2   Baseball & Softball
3             4                       2            Basketball
4             5                       2              Lacrosse
5             6                       2      Tennis & Racquet
6             7                       2                Hockey
7             8                       2           More Sports
8             9                       3      Cardio Equipment
9            10                       3     Strength Training
10           11                       3   Fitness Accessories
11           12                       3          Boxing & MMA
12           13                       3           Electronics
13           14                       3        Yoga & Pilates
14           15                       3     Training by Sport
15           16                       3       As Seen on  TV!
16           17                       4                Cleats
17           18                       4        Men's Footwear
18           19                       4      Women's Footwear
19           20                       4        Kids' Footwear
20           21                       4        Featured Shops
21           22                       4           Accessories
22           23                       5         Men's Apparel
23           24                       5       Women's Apparel
24           25                       5         Boys' Apparel
25           26                       5        Girls' Apparel
26           27                       5           Accessories
27           28                       5            Top Brands
28           29                       5         Shop By Sport
29           30                       6      Men's Golf Clubs
30           31                       6    Women's Golf Clubs
31           32                       6          Golf Apparel
32           33                       6            Golf Shoes
33           34                       6     Golf Bags & Carts
34           35                       6           Golf Gloves
35           36                       6            Golf Balls
36           37                       6           Electronics
37           38                       6      Kids' Golf Clubs
38           39                       6             Team Shop
39           40                       6           Accessories
40           41                       6              Trade-In
41           42                       7     Bike & Skate Shop
42           43                       7      Camping & Hiking
43           44                       7    Hunting & Shooting
44           45                       7               Fishing
45           46                       7  Indoor/Outdoor Games
46           47                       7               Boating
47           48                       7          Water Sports
48           49                       8                   MLB
49           50                       8                   NFL
50           51                       8                   NHL
51           52                       8                   NBA
52           53                       8                  NCAA
53           54                       8                   MLS
54           55                       8  International Soccer
55           56                       8        World Cup Shop
56           57                       8           MLB Players
57           58                       8           NFL Players

In [20]:
departments = pd.read_csv('retail_db/departments/part-00000.txt',names = departments_columns)
departments

   department_id department_name
0              2         Fitness
1              3        Footwear
2              4         Apparel
3              5            Golf
4              6        Outdoors
5              7        Fan Shop

In [21]:
base_dir= 'retail_db_json'

In [22]:
file = src_file_name[0]

file_path_list = re.split(r'\\',file)
db_name = file_path_list[-2]
db_name

'categories'

In [23]:
file_name = file_path_list[-1]
file_name

'part-00000.txt'

In [24]:
f'{base_dir}/{db_name}/{file_name}'

'retail_db_json/categories/part-00000.txt'

In [25]:
src_file_names = glob.glob("retail_db/*/part-*")
src_file_names

['retail_db\\categories\\part-00000.txt',
 'retail_db\\customers\\part-000001.txt',
 'retail_db\\departments\\part-00000.txt',
 'retail_db\\orders\\part-00000.txt',
 'retail_db\\order_items\\part-order_items.txt',
 'retail_db\\products\\part-products.txt']

In [26]:
src_file_names = glob.glob("retail_db/*/part-*")
src_file_names
for file in src_file_name:
    file_path_list = re.split(r'\\',file)
    ds_name = file_path_list[1]
    file_name = file_path_list[-1]
    json_file_path = f'{base_dir}/{ds_name}/{file_name}'
    print(json_file_path)

retail_db_json/categories/part-00000.txt
retail_db_json/customers/part-000001.txt
retail_db_json/departments/part-00000.txt
retail_db_json/orders/part-00000.txt
retail_db_json/order_items/part-order_items.txt
retail_db_json/products/part-products.txt

In [27]:
import pandas as pd
columns= ['order_id','order_date','order_customer_id','order_status']

In [28]:
df = pd.read_csv('retail_db/orders/part-00000.txt',names = columns)

In [29]:
df.head()

   order_id             order_date  order_customer_id     order_status
0         1  2013-07-25 00:00:00.0              11599           CLOSED
1         2  2013-07-25 00:00:00.0                256  PENDING_PAYMENT
2         3  2013-07-25 00:00:00.0              12111         COMPLETE
3         4  2013-07-25 00:00:00.0               8827           CLOSED
4         5  2013-07-25 00:00:00.0              11318         COMPLETE

In [30]:
import os 
os.makedirs('retail_db/orders',exist_ok= True)

In [31]:
file_path_list

['retail_db', 'products', 'part-products.txt']

In [32]:
base_dir

'retail_db_json'

In [37]:
for file in src_file_name:
    print(f'Processing {file}') 
    file_path_list = re.split(r'\\',file)
    ds_name = file_path_list[-2]
    columns = get_column_name(schemas, ds_name)
    df = pd.read_csv(file, names = columns)
    print(f'Shape of {ds_name} is {df.shape}')

Processing retail_db\categories\part-00000.txt
Shape of categories is (58, 3)
Processing retail_db\customers\part-000001.txt
Shape of customers is (12435, 9)
Processing retail_db\departments\part-00000.txt
Shape of departments is (6, 2)
Processing retail_db\orders\part-00000.txt
Shape of orders is (68883, 4)
Processing retail_db\order_items\part-order_items.txt
Shape of order_items is (172198, 6)
Processing retail_db\products\part-products.txt
Shape of products is (1345, 6)

In [38]:
import os

In [39]:
base_dir

'retail_db_json'

In [43]:
for file in src_file_name:
    print(f'Processing {file}') 
    file_path_list = re.split(r'\\',file)
    ds_name = file_path_list[-2]
    file_name = file_path_list[-1]
    json_file_path = f'{base_dir}/{ds_name}/{file_name}'
    columns = get_column_name(schemas, ds_name)
    df = pd.read_csv(file, names = columns)
    os.makedirs(f'{base_dir}/{ds_name}',exist_ok= True) 
    df.to_json(json_file_path,orient = 'records',lines = True)

Processing retail_db\categories\part-00000.txt
Processing retail_db\customers\part-000001.txt
Processing retail_db\departments\part-00000.txt
Processing retail_db\orders\part-00000.txt
Processing retail_db\order_items\part-order_items.txt
Processing retail_db\products\part-products.txt